### ISSUE TITLE
Daemonize failed because unable to lock pid file 

### ISSUE THREAD

**Issue by hadoop835** [Tencent/tat-agent#17]
![image](https://user-images.githubusercontent.com/8055054/212024404-c94ad2d9-b64f-40a2-8fed-9a9db4f941b1.png)

**Comment by xiaoquanju** [comment]
感觉是你启动了多个进程 文件被占用导致的

**Comment by hadoop835** [comment]
@xiaoquanju 启动不了

> 感觉是你启动了多个进程 文件被占用导致的
