### ISSUE TITLE
Docker打包的时候无法访问基础镜像

### ISSUE THREAD

**Issue by Jesn** [Tencent/tat-agent#23]
![image](https://github.com/Tencent/tat-agent/assets/5728274/0afe83a9-47dc-4681-8c15-ae62ed95739c)

ERROR [internal] load metadata for csighub.tencentyun.com/tat-develop/library:centos-base

**Comment by xiaoquanju** [comment]
嗯 这个后面优化下

**Comment by Mota-Link** [comment]
已解决
